credentials:
  system:
    domainCredentials:
      - credentials:
        - file:
            scope: GLOBAL
            fileName: oscontainer-secret
            id: oscontainer-secret
            # Secret must be base64-encoded
            # See: https://github.com/jenkinsci/configuration-as-code-plugin/issues/884
            secretBytes: "${base64:${oscontainer-secret/dockerconfig}}"
            description: Push secret for quay.io/coreos-assembler/fcos

